version: "3.9"
services:
  mysql:
    build:
      context: .
      dockerfile: DockerFile
    container_name: cinema_container_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "acuni"